# Dependencies
gems:             [jekyll-paginate]


# Permalinks
permalink:        pretty

# Setup
title:            Project ajda
tagline:          'A tool for news sceptics'
description:      'Part of the for the <a href="http://bbcnewslabs.co.uk/projects/trust-project-challenge/">Trust Project Challenge Hackathon</a>. '
url:              https://dpa-newslab.github.io/ajda
baseurl:          /ajda/

author:
  name:           'Julia Kilian, Fabian Schmidt, Martin Virtel'
  url:            http://newsstreamproject.org/

paginate:         5

# Custom vars
version:          2.1.0

github:
